name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: WeThinkCode_ Send Twist Webooks
      uses: crbaker/actions-twister@v1.7
      with:
        install-id: 143902
        install-token: 143902_ef42b95d5d6a04c43c1b3bd045068567
        title: Some Title
        content: >
          I **hope** that _you_ like long line  \n* of text that spans many lines<br>this is a line\s\s\nDon't hate the haters
